/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import type { ProjectInfo } from "../project/project";
import { useNavigate } from "react-router";
import type { cursorState } from "./cherry-lamp-container";
import { useContext } from "react";
import { HomeContext } from "../../contexts/home-context";
import {
  CherryMaterial,
  LampMaterial,
  StemMaterial,
} from "./cherry-lamp-materials";

export function Model({
  cherries,
  setCursorState,
  ...props
}: {
  cherries: ProjectInfo[];
  setCursorState: (cursorState: cursorState) => void;
}) {
  const { nodes } = useGLTF("/lamp_0811.glb");
  const { setProjectOnDisplay } = useContext(HomeContext);
  const navigate = useNavigate();
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stem_9.geometry}
        material={nodes.Stem_9.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Stem 9" }}
      >
        <StemMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cherry_9.geometry}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Cherry 9" }}
      >
        <CherryMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamp.geometry}
        material={nodes.Lamp.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Lamp" }}
      >
        <LampMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stem_0.geometry}
        material={nodes.Stem_0.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Stem 0" }}
      >
        <StemMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cherry_0.geometry}
        material={nodes.Cherry_0.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Cherry 0" }}
      >
        <CherryMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cherry_1.geometry}
        material={nodes.Cherry_1.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Cherry 1", cherryId: 0 }}
        onClick={(event) => {
          event.stopPropagation();
          navigate(
            cherries[event.object.userData.cherryId]
              ? `/projects/${cherries[event.object.userData.cherryId].id}`
              : ""
          );
        }}
        onPointerOver={(event) => {
          setCursorState("hover");
          setProjectOnDisplay?.(cherries[event.object.userData.cherryId]);
        }}
        onPointerOut={() => {
          setCursorState(null);
          setProjectOnDisplay?.(null);
        }}
      >
        <CherryMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stem_1.geometry}
        material={nodes.Stem_1.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Stem 1" }}
      >
        <StemMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stem_5.geometry}
        material={nodes.Stem_5.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Stem 5" }}
      >
        <StemMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cherry_5.geometry}
        material={nodes.Cherry_5.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Cherry 5" }}
      >
        <CherryMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stem_4.geometry}
        material={nodes.Stem_4.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Stem 4" }}
      >
        <StemMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cherry_4.geometry}
        material={nodes.Cherry_4.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Cherry 4" }}
      >
        <CherryMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stem_3.geometry}
        material={nodes.Stem_3.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Stem 3" }}
      >
        <StemMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cherry_3.geometry}
        material={nodes.Cherry_3.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Cherry 3" }}
      >
        <CherryMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stem_2.geometry}
        material={nodes.Stem_2.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Stem 2" }}
      >
        <StemMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cherry_2.geometry}
        material={nodes.Cherry_2.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Cherry 2" }}
      >
        <CherryMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stem_10.geometry}
        material={nodes.Stem_10.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Stem 10" }}
      >
        <StemMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cherry_10.geometry}
        material={nodes.Cherry_10.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Cherry 10" }}
      >
        <CherryMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stem_11.geometry}
        material={nodes.Stem_11.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Stem 11" }}
      >
        <StemMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cherry_11.geometry}
        material={nodes.Cherry_11.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Cherry 11" }}
      >
        <CherryMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stem_6.geometry}
        material={nodes.Stem_6.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Stem 6" }}
      >
        <StemMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cherry_6.geometry}
        material={nodes.Cherry_6.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Cherry 6" }}
      >
        <CherryMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stem_14.geometry}
        material={nodes.Stem_14.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Stem 14" }}
      >
        <StemMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cherry_14.geometry}
        material={nodes.Cherry_14.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Cherry 14" }}
      >
        <CherryMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stem_8.geometry}
        material={nodes.Stem_8.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Stem 8" }}
      >
        <StemMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cherry_8.geometry}
        material={nodes.Cherry_8.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Cherry 8" }}
      >
        <CherryMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stem_13.geometry}
        material={nodes.Stem_13.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Stem 13" }}
      >
        <StemMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cherry_13.geometry}
        material={nodes.Cherry_13.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Cherry 13" }}
      >
        <CherryMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stem_12.geometry}
        material={nodes.Stem_12.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Stem 12" }}
      >
        <StemMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cherry_12.geometry}
        material={nodes.Cherry_12.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Cherry 12" }}
      >
        <CherryMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stem_7.geometry}
        material={nodes.Stem_7.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Stem 7" }}
      >
        <StemMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cherry_7.geometry}
        material={nodes.Cherry_7.material}
        position={[8.484, 14.508, -3.527]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.282}
        userData={{ name: "Cherry 7" }}
      >
        <CherryMaterial />
      </mesh>
    </group>
  );
}

useGLTF.preload("/lamp_0811.glb");
