/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { MeshTransmissionMaterial, useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/lamp2.glb");
  return (
    <group {...props} dispose={null} scale={3}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ084"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      >
        <MeshTransmissionMaterial
          backside
          backsideThickness={5}
          thickness={2}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ001"].geometry}
        material={materials["Cherry Stem"]}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ002"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ003"].geometry}
        material={materials.Cherry}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ004"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ005"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ006"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ007"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ013"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ014"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ015"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ016"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ017"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ018"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ019"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ021"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ022"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ023"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ024"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ025"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ026"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ027"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ028"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ029"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ030"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ031"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ032"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ033"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ034"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ035"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ036"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ037"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ038"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ054"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ055"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ060"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ061"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ062"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ063"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ064"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ065"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ066"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ067"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ068"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ069"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ070"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ071"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ072"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ073"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.885, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ079"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ105"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ106"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.885, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ110"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ111"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ112"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ113"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ114"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ115"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ116"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.885, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ117"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ118"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ119"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ120"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.885, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ121"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ122"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ123"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ124"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ125"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ126"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ127"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ133"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.885, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ136"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ142"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ143"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ144"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ145"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.885, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ146"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ349"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ350"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ594"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ595"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ596"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ597"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ598"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ599"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ600"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ601"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ602"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ603"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ604"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ605"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ606"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ607"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ608"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ611"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ612"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ613"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ614"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ615"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ616"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ617"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ618"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ619"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ620"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ621"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ622"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ623"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ624"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ625"].geometry}
        material={materials["Cherry Stem"]}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ626"].geometry}
        material={materials.Cherry}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ627"].geometry}
        material={materials.Cherry}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ628"].geometry}
        material={materials["Cherry Stem"]}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ629"].geometry}
        material={materials["Cherry Stem"]}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ630"].geometry}
        material={materials.Cherry}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ631"].geometry}
        material={materials["Cherry Stem"]}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ632"].geometry}
        material={materials.Cherry}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ637"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ638"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ639"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ640"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ642"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ643"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ644"].geometry}
        material={materials["Cherry Stem"]}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ645"].geometry}
        material={materials.Cherry}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ646"].geometry}
        material={materials["Cherry Stem"]}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ647"].geometry}
        material={materials.Cherry}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ650"].geometry}
        material={materials["Cherry Stem"]}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ651"].geometry}
        material={materials.Cherry}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ652"].geometry}
        material={materials["Cherry Stem"]}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ653"].geometry}
        material={materials.Cherry}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ654"].geometry}
        material={materials["Cherry Stem"]}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ655"].geometry}
        material={materials.Cherry}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ656"].geometry}
        material={materials["Cherry Stem"]}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ657"].geometry}
        material={materials.Cherry}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ662"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ663"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ664"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ665"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ666"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ667"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ668"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ669"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ670"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ671"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ672"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ673"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ674"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ675"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ676"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ677"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ678"].geometry}
        material={materials["Cherry Stem"]}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ679"].geometry}
        material={materials.Cherry}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ680"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ681"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ682"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ683"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ684"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ685"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ686"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ687"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ688"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ689"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ690"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ691"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["SAN-ZW-2-OBJ692"].geometry}
        material={materials.Acrylic}
        position={[1.083, 1.542, -0.483]}
        rotation={[-1.593, -0.013, 0.314]}
        scale={0.036}
      />
    </group>
  );
}

useGLTF.preload("/lamp2.glb");
