/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAboutRouteImport } from './routes/admin/about'
import { Route as LayoutProjectsRouteImport } from './routes/_layout.projects'
import { Route as LayoutHomeRouteImport } from './routes/_layout.home'
import { Route as LayoutAboutRouteImport } from './routes/_layout.about'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as AdminProjectsPublishRouteImport } from './routes/admin/projects/publish'
import { Route as LayoutProjectsProjectIdRouteImport } from './routes/_layout.projects.$projectId'
import { Route as AdminProjectsProjectIdIndexRouteImport } from './routes/admin/projects/$projectId/index'
import { Route as AdminProjectsProjectIdMediasRouteImport } from './routes/admin/projects/$projectId/medias'
import { Route as AdminProjectsProjectIdInfoRouteImport } from './routes/admin/projects/$projectId/info'
import { Route as AdminProjectsProjectIdDescriptionRouteImport } from './routes/admin/projects/$projectId/description'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAboutRoute = AdminAboutRouteImport.update({
  id: '/admin/about',
  path: '/admin/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutProjectsRoute = LayoutProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHomeRoute = LayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/admin/projects/',
  path: '/admin/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsPublishRoute = AdminProjectsPublishRouteImport.update({
  id: '/admin/projects/publish',
  path: '/admin/projects/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutProjectsProjectIdRoute = LayoutProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => LayoutProjectsRoute,
} as any)
const AdminProjectsProjectIdIndexRoute =
  AdminProjectsProjectIdIndexRouteImport.update({
    id: '/admin/projects/$projectId/',
    path: '/admin/projects/$projectId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminProjectsProjectIdMediasRoute =
  AdminProjectsProjectIdMediasRouteImport.update({
    id: '/admin/projects/$projectId/medias',
    path: '/admin/projects/$projectId/medias',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminProjectsProjectIdInfoRoute =
  AdminProjectsProjectIdInfoRouteImport.update({
    id: '/admin/projects/$projectId/info',
    path: '/admin/projects/$projectId/info',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminProjectsProjectIdDescriptionRoute =
  AdminProjectsProjectIdDescriptionRouteImport.update({
    id: '/admin/projects/$projectId/description',
    path: '/admin/projects/$projectId/description',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof LayoutAboutRoute
  '/home': typeof LayoutHomeRoute
  '/projects': typeof LayoutProjectsRouteWithChildren
  '/admin/about': typeof AdminAboutRoute
  '/admin/': typeof AdminIndexRoute
  '/projects/$projectId': typeof LayoutProjectsProjectIdRoute
  '/admin/projects/publish': typeof AdminProjectsPublishRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/projects/$projectId/description': typeof AdminProjectsProjectIdDescriptionRoute
  '/admin/projects/$projectId/info': typeof AdminProjectsProjectIdInfoRoute
  '/admin/projects/$projectId/medias': typeof AdminProjectsProjectIdMediasRoute
  '/admin/projects/$projectId/': typeof AdminProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof LayoutAboutRoute
  '/home': typeof LayoutHomeRoute
  '/projects': typeof LayoutProjectsRouteWithChildren
  '/admin/about': typeof AdminAboutRoute
  '/admin': typeof AdminIndexRoute
  '/projects/$projectId': typeof LayoutProjectsProjectIdRoute
  '/admin/projects/publish': typeof AdminProjectsPublishRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/projects/$projectId/description': typeof AdminProjectsProjectIdDescriptionRoute
  '/admin/projects/$projectId/info': typeof AdminProjectsProjectIdInfoRoute
  '/admin/projects/$projectId/medias': typeof AdminProjectsProjectIdMediasRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/home': typeof LayoutHomeRoute
  '/_layout/projects': typeof LayoutProjectsRouteWithChildren
  '/admin/about': typeof AdminAboutRoute
  '/admin/': typeof AdminIndexRoute
  '/_layout/projects/$projectId': typeof LayoutProjectsProjectIdRoute
  '/admin/projects/publish': typeof AdminProjectsPublishRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/projects/$projectId/description': typeof AdminProjectsProjectIdDescriptionRoute
  '/admin/projects/$projectId/info': typeof AdminProjectsProjectIdInfoRoute
  '/admin/projects/$projectId/medias': typeof AdminProjectsProjectIdMediasRoute
  '/admin/projects/$projectId/': typeof AdminProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/home'
    | '/projects'
    | '/admin/about'
    | '/admin/'
    | '/projects/$projectId'
    | '/admin/projects/publish'
    | '/admin/projects/'
    | '/admin/projects/$projectId/description'
    | '/admin/projects/$projectId/info'
    | '/admin/projects/$projectId/medias'
    | '/admin/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/home'
    | '/projects'
    | '/admin/about'
    | '/admin'
    | '/projects/$projectId'
    | '/admin/projects/publish'
    | '/admin/projects'
    | '/admin/projects/$projectId/description'
    | '/admin/projects/$projectId/info'
    | '/admin/projects/$projectId/medias'
    | '/admin/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/about'
    | '/_layout/home'
    | '/_layout/projects'
    | '/admin/about'
    | '/admin/'
    | '/_layout/projects/$projectId'
    | '/admin/projects/publish'
    | '/admin/projects/'
    | '/admin/projects/$projectId/description'
    | '/admin/projects/$projectId/info'
    | '/admin/projects/$projectId/medias'
    | '/admin/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  AdminAboutRoute: typeof AdminAboutRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProjectsPublishRoute: typeof AdminProjectsPublishRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  AdminProjectsProjectIdDescriptionRoute: typeof AdminProjectsProjectIdDescriptionRoute
  AdminProjectsProjectIdInfoRoute: typeof AdminProjectsProjectIdInfoRoute
  AdminProjectsProjectIdMediasRoute: typeof AdminProjectsProjectIdMediasRoute
  AdminProjectsProjectIdIndexRoute: typeof AdminProjectsProjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/about': {
      id: '/admin/about'
      path: '/admin/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/projects': {
      id: '/_layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LayoutProjectsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/home': {
      id: '/_layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutHomeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/admin/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/publish': {
      id: '/admin/projects/publish'
      path: '/admin/projects/publish'
      fullPath: '/admin/projects/publish'
      preLoaderRoute: typeof AdminProjectsPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/projects/$projectId': {
      id: '/_layout/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof LayoutProjectsProjectIdRouteImport
      parentRoute: typeof LayoutProjectsRoute
    }
    '/admin/projects/$projectId/': {
      id: '/admin/projects/$projectId/'
      path: '/admin/projects/$projectId'
      fullPath: '/admin/projects/$projectId/'
      preLoaderRoute: typeof AdminProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/$projectId/medias': {
      id: '/admin/projects/$projectId/medias'
      path: '/admin/projects/$projectId/medias'
      fullPath: '/admin/projects/$projectId/medias'
      preLoaderRoute: typeof AdminProjectsProjectIdMediasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/$projectId/info': {
      id: '/admin/projects/$projectId/info'
      path: '/admin/projects/$projectId/info'
      fullPath: '/admin/projects/$projectId/info'
      preLoaderRoute: typeof AdminProjectsProjectIdInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/$projectId/description': {
      id: '/admin/projects/$projectId/description'
      path: '/admin/projects/$projectId/description'
      fullPath: '/admin/projects/$projectId/description'
      preLoaderRoute: typeof AdminProjectsProjectIdDescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutProjectsRouteChildren {
  LayoutProjectsProjectIdRoute: typeof LayoutProjectsProjectIdRoute
}

const LayoutProjectsRouteChildren: LayoutProjectsRouteChildren = {
  LayoutProjectsProjectIdRoute: LayoutProjectsProjectIdRoute,
}

const LayoutProjectsRouteWithChildren = LayoutProjectsRoute._addFileChildren(
  LayoutProjectsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutHomeRoute: typeof LayoutHomeRoute
  LayoutProjectsRoute: typeof LayoutProjectsRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutHomeRoute: LayoutHomeRoute,
  LayoutProjectsRoute: LayoutProjectsRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  AdminAboutRoute: AdminAboutRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProjectsPublishRoute: AdminProjectsPublishRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  AdminProjectsProjectIdDescriptionRoute:
    AdminProjectsProjectIdDescriptionRoute,
  AdminProjectsProjectIdInfoRoute: AdminProjectsProjectIdInfoRoute,
  AdminProjectsProjectIdMediasRoute: AdminProjectsProjectIdMediasRoute,
  AdminProjectsProjectIdIndexRoute: AdminProjectsProjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
